export const skillsList = [
  {
    category: 'AWS',
    skills: [
      'Lambda',
      'App Runner',
      'EC2',
      'EKS',
      'S3',
      'DynamoDB',
      'ECR',
      'SQS',
      'Coginto',
      'IAM',
      'API Gateway',
      'Cloudfront',
      'Route53',
      'Cloudwatch',
      'ACM',
      'WAF',
    ],
  },
  {
    category: 'Frontend',
    skills: [
      'React',
      'Next.js',
      'React Native',
      'Typescript',
      'Angular',
      'NgRx',
      'NativeScript',
      'Web Components',
      'HTML 5',
      'SCSS',
      'CSS Modules',
      'Styled Components',
      'Storybook',
      'Design Systems',
    ],
  },
  {
    category: 'Google Cloud',
    skills: [
      'Firebase',
      'Firestore',
      'Cloud Storage',
      'Firebase Authentication',
      'Cloud Run',
      'App Engine',
      'Cloud Functions',
      'IAM',
      'Artifact Registry',
      'Big Query',
      'Pub/Sub',
      'KMS',
    ],
  },
  {
    category: 'Backend',
    skills: [
      'Node.js',
      'Express.js',
      'Electron',
      "REST API's",
      'Python',
      'Flask',
      'Fast API',
    ],
  },
  {
    category: 'DevOps',
    skills: [
      'Terraform',
      'Docker',
      'Kubernetes',
      'Microservices',
      'CI/CD',
      'CircleCI',
      'Github Actions',
      'Gitlab CI',
      'Bitbucket pipelines',
    ],
  },
  {
    category: 'Testing & Tooling',
    skills: [
      'Jest',
      'React Testing Library',
      'Cypress',
      'Chromatic',
      'Puppeteer',
      'Playwright',
      'Jasmine',
      'Mocha',
      'Supertest',
      'Pytest',
      'Git',
      'Bash/Shell',
      'Webpack',
      'NPM',
      'Yarn',
      'Prettier',
      'ESLint',
      'PIP',
      'Swagger Docs',
      'Postman',
    ],
  },
];
